export default {
  GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
  GET_INPUT_LOCATION: 'GET_INPUT_LOCATION',
  TOGGLE_SEARCH_RESULT: 'TOGGLE_SEARCH_RESULT',
  GET_ADDRESS_PREDICTIONS : 'GET_ADDRESS_PREDICTIONS'
};
